---
arch: amd64
os: linux
dist: focal
language: cpp
compiler: gcc
env:
  global:
    - VCPKG_TRIPLET=x64-linux VCPKG_BUILD_TYPE=release CMAKE_BUILD_PARALLEL_LEVEL=2 MAKEFLAGS="-j 2"

git:
  strategy: clone
  depth: false

addons:
  sonarcloud:
    organization: opentibiabr
    token:
      secure: XeUyt0Kacat0i/GJHAmyQmQGFBR/3CMYfw06iXMIkjy3fsORb0aF2P711Nh+DnaVsR+aEOBLTm2jKS52g+AQ9OjXGzvv20UYbRBc0yU7PxyXVJwkAbcqtXMddYSyQQA7uAWTpkI72nLK03t8pXZJlwals7HutdyN1bmhkc04ZP9W3QVKTwQAuG246vhiI7/gYTrM5rTsxP/zf9ur2kjx2M3rug41WqM9CdPxbJN6ozr0O0YTOXXBiez3L224BkqKlS6OFcMkDXEnTv5MXK2jQjPya9R06uShK0KC4KsDkfmS64x6wgX8nTGvkOKGH6oMhEB+dHHJ8zD4vsxmCqk1muK7uVrBKqAACIWfkOdAsCBypYZJO4CPlaoSb/gsKGfCGWK59iUfpALSBvMsar8vkYZ15nVuOdQmpv+Feyauh5vVro4SwS17VALLEj52TPdcrE40Gpa5YGkT9iCwAQxvxcEBcrDoB0QUaanC5hsXZVxrKc9QHZZkv+d9ay0FdwwvZZ0oCWA+nb5pLY0dkOq26OgdWo4/fjRB7YGm+vjxnN1rI4bT2wGUmp616iAd11J5DI4dwvy+m9/4xSkapkVXW7lRklg9XmZZAovRSBUeh4eE+zGfB/cc3gzS0x74tR5ubyekGjzhMdupYbj6cAdwlDJRw3cgmJQ9qjmBPBWmfuk=
  apt:
    update: true
    packages:
      - ccache
      - build-essential
      - cmake
      - libluajit-5.1-dev
      - tar
      - curl
      - zip
      - unzip

install:
  - cd $HOME
  - git clone https://github.com/microsoft/vcpkg || true
  - cd vcpkg ; git fetch ; git pull ; cd ..
  - ./vcpkg/bootstrap-vcpkg.sh
  - ./vcpkg/vcpkg integrate install

script:
  - cd /home/travis/build/opentibiabr/canary
  - export CXXFLAGS="$CXXFLAGS -DBOOST_ASIO_DISABLE_NOEXCEPT=1 "
  - $HOME/vcpkg/vcpkg --feature-flags=binarycaching,manifests,versions install
  - mkdir build
  - cd build
  - cmake -DCMAKE_TOOLCHAIN_FILE=$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake ..
  - cd ..
  - NUMBER_OF_PROCESSORS=$(nproc --all)
  - build-wrapper-linux-x86-64 --out-dir bw-output cmake --build build/
  - sonar-scanner -Dsonar.cfamily.cache.enabled=true -Dsonar.cfamily.cache.path=${TRAVIS_HOME}/.cfamily -Dsonar.cfamily.threads=${NUMBER_OF_PROCESSORS}

  # - sonar-scanner -Dsonar.cfamily.cache.enabled=true -Dsonar.cfamily.cache.path=${TRAVIS_HOME}/.cfamily -Dsonar.cfamily.threads=${NUMBER_OF_PROCESSORS} || true
  # - curl --upload-file /home/travis/build/opentibiabr/canary/sonar-cfamily-reproducer.zip https://transfer.sh/sonar-cfamily-reproducer.zip

cache:
  directories:
    - $HOME/.sonar/cache
    - $HOME/.cache
    - $HOME/.ccache
    - $HOME/.cfamily
    - $HOME/vcpkg
