name: Report a missing content
description: Any thing that is missing
title: "[Content]: "
labels: ["Status: Pending Test", "Type: Missing Content"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue!

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How critical is this?
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true

  - type: checkboxes
    id: area
    attributes:
      label: Area
      description: Where is the problem?
      options:
        - label: Datapack
        - label: Docker
        - label: Map
        - label: Source
    validations:
      required: true

  - type: textarea
    id: missing-content
    attributes:
      label: What is missing?
      description: Map, sprite, script, quest, teleport, monster, etc
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backtick.
      render: shell

  - type: textarea
    id: attach
    attributes:
      label: Attach any relevant file
      description: Attach screenshots, logs, etc, anything that can helps us

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/opentibiabr/canary/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
