--
version: "3.3"

services:
  server:
    build:
      context: ../
      dockerfile: docker/server/Dockerfile
    ports:
      - 7171:7171
      - 7172:7172
    depends_on:
      - mysql
      - website
      - login
    links:
      - mysql

  mysql:
    build:
      context: ../
      dockerfile: docker/mysql/Dockerfile
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=canary
      - MYSQL_USER=canary
      - MYSQL_PASSWORD=canary
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    ports:
      - 3306:3306

  website:
    image: webdevops/php-nginx:alpine-php7
    restart: unless-stopped
    environment:
      - WEB_DOCUMENT_ROOT=/tmp/web/
      - WEB_DOCUMENT_INDEX=index.php
    ports:
      - 8080:80
    volumes:
      - ./docker/data/web:/tmp/web
      - ./:/tmp/otserver/
    depends_on:
      - mysql

  login:
    build:
      context: ../
      dockerfile: docker/login/Dockerfile
    restart: unless-stopped
    volumes:
      - ./data/:/info/data/
    ports:
      - 80:8080
    depends_on:
      - mysql
    environment:
      - DB_HOSTNAME=mysql
      - DB_PORT=3306
      - DB_DATABASE=canary
      - DB_USERNAME=canary
      - DB_PASSWORD=canary
      - APP_PORT=8080
      - SERVER_PATH=/info/
      - SERVER_NAME=Canary
      - SERVER_IP=127.0.0.1
      - SERVER_PORT=7172
