---
name: Build - Windows

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

env:
  VCPKG_BUILD_TYPE: release
  CMAKE_BUILD_PARALLEL_LEVEL: 2
  MAKEFLAGS: '-j 2'

jobs:
  job:
    name: ${{ matrix.os }}-${{ matrix.buildtype }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, windows-2022]
        buildtype: [windows-release, windows-release-asan, windows-debug]
        include:
          - os: windows-2019
            triplet: x64-windows
            packages: >
              boost-asio boost-iostreams boost-system boost-filesystem
              boost-variant boost-lockfree cryptopp curl jsoncpp
              luajit libmariadb pugixml spdlog libzippp
          - os: windows-2022
            triplet: x64-windows
            packages: >
              boost-asio boost-iostreams boost-system boost-filesystem
              boost-variant boost-lockfree cryptopp curl jsoncpp
              luajit libmariadb pugixml spdlog libzippp

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Remove Windows pre-installed MySQL
        run: rm -r -fo C:/mysql*
        if: contains( matrix.os, 'windows')

      - name: Restore artifacts and install vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgGitCommitId: 773516ecf6014d89cc69b11bb54605ad4be56694

      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@latest

      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: ${{ matrix.buildtype }}
          buildPreset: ${{ matrix.buildtype }}

      - name: Create and Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: canary-${{ matrix.buildtype }}-${{ github.sha }}
          path: |
            ${{ github.workspace }}/build/${{ matrix.buildtype }}/bin/
